{% set name = "dimod" %}
{% set version = "0.12.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dimod-{{ version }}.tar.gz
  sha256: 1ff58655be3e127d359438e6d2f6564954a066eeafaf4de88135dcd4e02843ca

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0,<4                        # [build_platform != target_platform]
    - numpy
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0,<4
    - numpy
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - numpy >=1.17.3
    - python

test:
  imports:
    - dimod
    - dimod.testing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dimod
  summary: A shared API for binary quadratic model samplers.
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - extern/filereaderlp/LICENSE

extra:
  recipe-maintainers:
    - BastianZim
