{% set name = "dimod" %}
{% set version = "0.12.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dimod-{{ version }}.tar.gz
  sha256: 05b444dee34dc1e143d1ce3ea311609fff58822c7843456a5a9fe9d4bc32963e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.33,<3.0                  # [build_platform != target_platform]
    - numpy
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.33,<3.0
    - numpy
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - dimod
    - dimod.testing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dimod
  summary: A shared API for binary quadratic model samplers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
