{% set name = "dimod" %}
{% set version = "0.12.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dimod-{{ version }}.tar.gz
  sha256: 95c0e6b96a21d42fdf87a2ee123d3d0d4776eab9cbe1b1fa9521b5bba0242e5a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0,<4                        # [build_platform != target_platform]
    - numpy
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0,<4
    - numpy
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - numpy >=1.17.3
    - python

test:
  imports:
    - dimod
    - dimod.testing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dimod
  summary: A shared API for binary quadratic model samplers.
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - extern/filereaderlp/LICENSE

extra:
  recipe-maintainers:
    - BastianZim
